### PR TITLE
Set up HLint code scanning workflow.

### PR DESCRIPTION
**Pull request by chungyc**
After the idea was brought up on the [Haskell Discourse](https://discourse.haskell.org/t/scan-code-with-hlint-for-github-v1-0-0/6151/2?u=chungyc), how could I resist proposing the change?

HLint does suggest [improvements](https://github.com/chungyc/haskell-beginners-exercises/security/code-scanning?query=is%3Aopen+branch%3Ahlint), so there may need to be some [HLint configuration](https://github.com/ndmitchell/hlint/blob/master/README.md#customizing-the-hints) to better fit your preferences, unless you do like HLint's suggestions.

I have invited @chshersh as a collaborator for the forked repository so they can view its [code scanning dashboard](https://github.com/chungyc/haskell-beginners-exercises/security/code-scanning?query=is%3Aopen+branch%3Ahlint).

cc @chshersh

### CODE REVIEW

**Comment by chshersh** [comment]
Thanks for the great contribution, @chungyc! 👏🏻 

Looking forward to seeing this in action 🙂 

HLint warnings in the test suite indeed can be cleaned up. Everything else is intentional 👌🏻 

I see that the HLint scan job has failed on CI for this repo. Do you have any ideas why this could happen?

**Comment by chungyc** [comment]
The HLint workflow is failing when uploading the analysis results to GitHub due to lack of permissions.  Rightly so in my opinion, because it's the workflow in my forked repository that grants the permission, and the permission shouldn't be granted for this repository until it has actually been incorporated into this one (i.e., after you approve granting the permission for this repository).

**Comment by chshersh** [comment]
I tried enabling the workflows but CI is still failing. Do you know what else I need to configure in this repo to make the CI job pass in this PR?

image

image

**Comment by chungyc** [comment]
I think you need to merge the workflow into your repository, so that it's your repository granting the permissions to your own repository instead of my forked repository trying to get permissions to another repository.

If that doesn't work, the merge could always be reverted ....

**Review by chshersh — APPROVED** [review]
Okay, let's try to merge it then

**Comment by chshersh** [comment]
It works!

https://github.com/haskell-beginners-2022/exercises/security/code-scanning

**Pull request merged**
