### PR TITLE
Lecture 1 exercises

### PR DESCRIPTION
**Pull request by RubenVerg**
### Solutions for Lecture 1

(I would like to apologize for the [intentionally] bad code you can find in the files, I tried to put more idiomatic versions in comments. Also `Lecture2.hs` has some stuff in it but isn't done, don't bother reviewing it)

cc @chshersh @vrom911

### CODE REVIEW

**Comment by chshersh** [comment]
Hi @RubenVerg 👋🏻 

Don't worry about ugly code 🙂 
However, could you open a PR to your fork of this repository instead? As we can't merge your solutions here.

**Comment by RubenVerg** [comment]
wdym?

**Comment by chshersh** [comment]
@RubenVerg This PR is the PR to the `exercises` repository under the `haskell-beginners-2022` organization

image

I recommend opening PRs to your own work. You can find more details with instructions and screenshots in the README:

* https://github.com/haskell-beginners-2022/exercises#asking-for-feedback

**Comment by RubenVerg** [comment]
ah, so I should make a separate branch? will do this afternoon

**Comment by chshersh** [comment]
The new PR looks good. So I'm closing this.

**Comment by RubenVerg** [comment]
great, thanks!

**Pull request closed without merging**
